# Generated by Django 3.2.5 on 2021-07-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.CharField(max_length=30, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='expiration_date',
            field=models.CharField(max_length=30, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.CharField(max_length=30, verbose_name='key'),
        ),
    ]
