# Generated by Django 3.2.5 on 2021-07-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mos', '0002_auto_20210706_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
